### ISSUE TITLE
Access srcds console

### ISSUE THREAD

**Issue by wyozi** [suchipi/gmod-server-docker#1]
Running docker logs on the gmod server instance seems to print either outdated console output or no console output at all.

Is there a way to see the srcds console in realtime? docker attach doesn't seem to work either. I'm running Docker 1.5.0

**Comment by suchipi** [comment]
I haven't tried it with docker logs yet, but you can allocate a tty and input device to run it directly. Try

docker run -it -p 27015:27015/udp suchipi/gmod-server
